name: sw_project
description: SOCNETO Frontend

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.13.0

dev_dependencies:
  angular_test: ^2.2.0
  angular_router: ^2.0.0-alpha+21
  build_runner: ^1.3.0
  build_test: ^0.10.3
  build_web_compilers: ^1.1.0
  pedantic: ^1.0.0
  test: ^1.5.1
  sass_builder: ^2.0.0
  js: ^0.6.0
