version: '3'
services:

  topic-modelling-analyser:
    container_name: tma
    build: './analysers/topic_modeling'
    restart: always
    depends_on:
      - kafka
      - jms

  sentiment-analyser:
    container_name: se
    build: './analysers/sentiment_analysis'
    restart: always
    depends_on:
      - kafka
      - jms

  twitter-acquirer:
    container_name: tw-acquirer
    build: './acquisition/DataAcquirer'
    restart: always
    depends_on:
      - kafka
      - jms

  twitter-static-acquirer:
    container_name: tw-static-acquirer
    build:
      context: './acquisition/DataAcquirer'
      dockerfile: 'Dockerfile.custom'
    restart: always
    depends_on:
      - kafka
      - jms
    environment:
      - ASPNETCORE_ENVIRONMENT=MovieTweets

