FROM mcr.microsoft.com/dotnet/core/runtime:3.0

RUN dotnet publish -o out -c Release ConsoleApi.KafkaMock/ConsoleApi.KafkaMock.csproj

COPY out/ app/

ENTRYPOINT ["dotnet", "ConsoleApi.KafkaMock.dll" "commands.json", "job_management.job_configuration.DataAcquirer_Twitter"]