FROM mcr.microsoft.com/dotnet/core/runtime:2.2

COPY app/bin/Release/netcoreapp2.2/publish/ app/

ENTRYPOINT ["dotnet", "ConsoleApi.KafkaMock.dll" "commands.json", "job_management.job_configuration.DataAcquirer_Twitter"]