version: '3'
services:

  frontend:
    environment:
      FRONTEND_ENV=prod101

  topic-modelling-analyser:
    container_name: tma
    build: '../analysers/topic_modeling'
    restart: always
    depends_on:
      - kafka
      - jms

  twitter-static-acquirer:
    container_name: tw-static-acquirer
    build:
      context: '../acquisition/DataAcquirer'
      dockerfile: 'Dockerfile.custom'
    restart: always
    depends_on:
      - kafka
      - jms
    environment:
      - ASPNETCORE_ENVIRONMENT=MovieTweets
 
