version: '3'

networks:
  kafka-network:
    external:
      name: kafka-network

services:

#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - kafka-network
#
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes # TODO remove
#    container_name: kafka_server
#    networks:
#      - kafka-network

  db:
    image: "postgres"
    container_name: storagedb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=storagedb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - kafka-network

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - kafka-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - kafka-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - 5601:5601
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - kafka-network

  logstash:
    build: ./docker/logstash/
    ports:
      - "9600:9600"
      - "9999:9999"
    environment:
      xpack.monitoring.elasticsearch.hosts: http://elasticsearch:9200
    networks:
      - kafka-network

#    driver: local

#  storage:
#    build: '.'
#    ports:
#      - '8888:8888'
#    container_name: storageservice
#    networks:
#      - kafka-network

volumes:
  data01:
