version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    depends_on:
      - kafka
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
  kibana:
    depends_on:
      - logstash
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - 5601:5601
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  logstash:
    build: ./docker/logstash/
    depends_on:
      - elasticsearch
    ports:
      - "9600:9600"
      - "9999:9999"
    environment:
      xpack.monitoring.elasticsearch.hosts: http://elasticsearch:9200

#    driver: local

#  storage:
#    build: '.'
#    ports:
#      - '8888:8888'
#    container_name: storageservice
#    networks:
#      - kafka-network

volumes:
  data01:
