FROM python:3.8

WORKDIR /usr/src/app

COPY ./ ./

#RUN pip install numpy==1.18.1
RUN pip install --default-timeout=120 --no-cache-dir --trusted-host pypi.python.org -r requirements.txt
RUN pip install en_core_web_lg-2.2.5.tar.gz

CMD [ "python", "./main.py", "--server_address","kafka:9092"]