FROM python:3.8

WORKDIR /usr/src/app

COPY ./*.py ./
COPY ./requirements.txt ./
COPY ./prepare.sh ./

RUN sh ./prepare.sh

CMD [ "python", "./main.py", "--server_address","kafka:9092" , "--sleep_on_startup"]
